version: '3.9'
services:
  react-template:
    container_name: 'keyword-search-react'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: "1000"
        WWWGROUP: "1000"
        NODE_VERSION: "${NODE_VERSION:-18.12.1}"
    restart: always
    stdin_open: true
    environment:
      TIME_ZONE: '${TIME_ZONE:-Asia/Seoul}'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - react
networks:
  react:
    driver: bridge
