import {
  getGroups,
  getUsersByGroup,
  searchUser,
  getUsersState,
  setUsers,
  setGroups,
  getGroup,
  setGroup,
  setGroupPermission,
  getEditGroup,
  setEditGroup,
  getPermList,
  setPermList,
  getEditUser,
  setEditUser,
  saveUser,
  saveGroup,
  resetPassword,
} from './usersReducer';

const usersModule = {
  getGroups,
  getUsersByGroup,
  searchUser,
  getUsersState,
  setUsers,
  setGroups,
  getGroup,
  setGroup,
  setGroupPermission,
  getEditGroup,
  setEditGroup,
  getPermList,
  setPermList,
  getEditUser,
  setEditUser,
  saveUser,
  saveGroup,
  resetPassword,
};

export default usersModule;
